### ISSUE TITLE
Practice problem: Click behavior

### ISSUE THREAD

**Issue by frankzx** [google-developer-training/basic-android-kotlin-compose-training-lemonade#1]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-button-click-practice-problem?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-button-click-practice-problem#0

**In which task and step of the codelab can this issue be found?**
Practice:Click behavior -> [1. Before you begin]

**Describe the problem**
typo:

> Remember that the solution is only one way to build the Lemonade app, so it's completely valid to build it a different way as long as the app requirements are met.

should be 

> Remember that the solution is NOT the only one way to build the Lemonade app, so it's completely valid to build it a different way as long as the app requirements are met.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by correabuscar** [comment]
Both variants sound valid to me, though.

**Comment by johnshea** [comment]
Hi @frankzx.

Thank you for sharing your concern with us.

I passed it along to the team so they can improve the wording as needed.

Hope you are enjoying the course!

Regards.
