### ISSUE TITLE
Practice problem: Click behavior - Link to download the zip file containing the images is broken

### ISSUE THREAD

**Issue by varad64** [google-developer-training/basic-android-kotlin-compose-training-lemonade#4]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-button-click-practice-problem?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-button-click-practice-problem#2

**In which task and step of the codelab can this issue be found?**
Task 3: Get Started
Sub-task - Add Images
Step 1: Link to download the zip file of the images is broken.

**Describe the problem**
https://github.com/google-developer-training/basic-android-kotlin-compose-training-lemonade/raw/main/lemonade_images.zip 

The above link to download the zip file is broken

**Steps to reproduce?**
1. Go to...  https://developer.android.com/codelabs/basic-android-kotlin-compose-button-click-practice-problem?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-button-click-practice-problem#2
2. Click on... zip file of the images hyperlink
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnshea** [comment]
Hi @varad64.

Thank you for letting us know of your issue.

I just checked and can confirm the download link is working as expected. I was able to download the zip file without any problem.

It is possible that link to GitHub raw files is blocked in your region of the world. I would suggest searching to see if that might be the case in your scenario.

Hope you are enjoying the course!

Regards.
