### ISSUE TITLE
Resource Link for images is broken

### ISSUE THREAD

**Issue by zachbuchli** [google-developer-training/basic-android-kotlin-compose-training-lemonade#9]
In the codelab for building the lemonade app, the link to download the zip files for the images does not work.

**Comment by rennawooo** [comment]
I found the images here: https://github.com/google-developer-training/basic-android-kotlin-compose-training-lemonade/blob/m2-main/lemonade_images.zip
They were in an old branch called m2-main.

**Comment by kronann** [comment]
Perfect, thank you !
